dist: focal
sudo: true
language: cpp

notifications:
  email:
    recipients:
      - john@smartypixels.com
      - john@johnernsthausen.com
      - johnernsthausen@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

script:
  - sudo apt-get install libgtest-dev
  - sudo apt-get install libgmock-dev
  - mkdir -p build
  - cd build
  - cmake .. 
  - make
  - ctest
