dist: focal
sudo: true
language: cpp

notifications:
  email:
    recipients:
      - john@smartypixels.com
      - john@johnernsthausen.com
      - johnernsthausen@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

before_install:
  - pip install --user cpp-coveralls

script:
  - sudo apt-get update -y
  - sudo apt-get install libgtest-dev
  - sudo apt-get install libgmock-dev
  - sudo apt-get install -y lcov
  - mkdir -p build
  - cd build
  - cmake .. 
  - make
  - ctest
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON
  - make -j 1
  - make coverage

after_success:
  - coveralls --gcov-options '\-lp'
