version: 2.1
executors:
  exectr:
    docker:
      - image: johnmernsthausen/cppwithgmockgtest:latest

jobs:
  build:
    executor: exectr
    steps:
      - run:
          name: Use this command in place of 'checkout' to clone repository into 'roc'
          command: |
            git clone https://github.com/JohnErnsthausen/roc.git
      - run:
          name: Setup cmake and build artifacts
          command: |
            cd roc
            mkdir build
            cd build
            cmake ..
            make
      - persist_to_workspace:
          root: .
          paths: roc

  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd roc
            cd build
            ./run
      - store_test_results:
          path: roc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
