version: 2.1
executors:
  exectr:
    docker:
      - image: johnmernsthausen/cppwithgmockgtest:latest

jobs:
  build:
    executor: exectr
    steps:
      - run:
          name: Use this command in place of 'checkout' to clone repository into 'roc'
          command: |
            git clone https://github.com/JohnErnsthausen/roc.git
      - run:
          name: Setup cmake and build artifacts
          command: |
            cd roc
            mkdir build
            cd build
            cmake ..
            make
      - persist_to_workspace:
          root: .
          paths: roc

  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd roc
            cd build
            ./run
      - store_test_results:
          path: roc

  coverage:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload Code Coverage Reports
          command: |
            curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
            gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
            shasum -a 256 -c codecov.SHA256SUM
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN}
            cd roc
            cd build
            ./codecov -cF coverage.info
             
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - build
            - test
