// SIXTERM_NUSE must be at least 4

#define TOPLINE_KSTART 10
#define TOPLINE_NUSE 7
#define SIXTERM_NUSE 7
#define SIXTERM_KSTART 10
#define THREETERM_NUSE 7
#define THREETERM_KSTART 10
#define MINTERMS 10
#define TOL 1e-10
